DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK_AUTHOR;

CREATE TABLE BOOK (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(400) NOT NULL,
  CONTENT_AS_TEXT CLOB,
  CONTENT_AS_PDF BLOB,
  PAGES_NUMBER INT,
  PUBLISH_DATE DATE,

 CONSTRAINT PK_BOOK PRIMARY KEY (ID)
);


CREATE TABLE AUTHOR (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  FIRST_NAME VARCHAR(200) NOT NULL,
  MIDDLE_NAME VARCHAR(200) NOT NULL,
  LAST_NAME VARCHAR(200) NOT NULL,
  DATE_OF_BIRTH TIMESTAMP NOT NULL,

  CONSTRAINT PK_AUTHOR PRIMARY KEY (ID)
);


CREATE TABLE BOOK_AUTHOR(
 AUTHOR_ID BIGINT NOT NULL,
 BOOK_ID BIGINT NOT NULL,

 CONSTRAINT PK_BOOK_AUTHOR PRIMARY KEY (AUTHOR_ID, BOOK_ID),
 CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
 CONSTRAINT FK_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID)
);

