/*
 * This file is generated by jOOQ.
 */
package ru.yusdm.training.jooq.jooqgenerated.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.yusdm.training.jooq.jooqgenerated.tables.JBook;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JBookRecord extends UpdatableRecordImpl<JBookRecord> implements Record6<Long, String, String, byte[], Integer, Timestamp> {

    private static final long serialVersionUID = -833992406;

    /**
     * Setter for <code>PUBLIC.BOOK.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.CONTENT_AS_TEXT</code>.
     */
    public void setContentAsText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.CONTENT_AS_TEXT</code>.
     */
    public String getContentAsText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.CONTENT_AS_PDF</code>.
     */
    public void setContentAsPdf(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.CONTENT_AS_PDF</code>.
     */
    public byte[] getContentAsPdf() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.PAGES_NUMBER</code>.
     */
    public void setPagesNumber(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.PAGES_NUMBER</code>.
     */
    public Integer getPagesNumber() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>PUBLIC.BOOK.PUBLISH_DATE</code>.
     */
    public void setPublishDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.BOOK.PUBLISH_DATE</code>.
     */
    public Timestamp getPublishDate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, byte[], Integer, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, byte[], Integer, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JBook.BOOK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JBook.BOOK.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JBook.BOOK.CONTENT_AS_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return JBook.BOOK.CONTENT_AS_PDF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return JBook.BOOK.PAGES_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return JBook.BOOK.PUBLISH_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContentAsText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getContentAsPdf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPagesNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getPublishDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContentAsText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getContentAsPdf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPagesNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getPublishDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JBookRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JBookRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JBookRecord value3(String value) {
        setContentAsText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JBookRecord value4(byte... value) {
        setContentAsPdf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JBookRecord value5(Integer value) {
        setPagesNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JBookRecord value6(Timestamp value) {
        setPublishDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JBookRecord values(Long value1, String value2, String value3, byte[] value4, Integer value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JBookRecord
     */
    public JBookRecord() {
        super(JBook.BOOK);
    }

    /**
     * Create a detached, initialised JBookRecord
     */
    public JBookRecord(Long id, String name, String contentAsText, byte[] contentAsPdf, Integer pagesNumber, Timestamp publishDate) {
        super(JBook.BOOK);

        set(0, id);
        set(1, name);
        set(2, contentAsText);
        set(3, contentAsPdf);
        set(4, pagesNumber);
        set(5, publishDate);
    }
}
