/*
 * This file is generated by jOOQ.
 */
package ru.yusdm.training.jooq.jooqgenerated.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.yusdm.training.jooq.jooqgenerated.Indexes;
import ru.yusdm.training.jooq.jooqgenerated.JPublic;
import ru.yusdm.training.jooq.jooqgenerated.Keys;
import ru.yusdm.training.jooq.jooqgenerated.tables.records.JAuthorRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JAuthor extends TableImpl<JAuthorRecord> {

    private static final long serialVersionUID = 1511643758;

    /**
     * The reference instance of <code>PUBLIC.AUTHOR</code>
     */
    public static final JAuthor AUTHOR = new JAuthor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JAuthorRecord> getRecordType() {
        return JAuthorRecord.class;
    }

    /**
     * The column <code>PUBLIC.AUTHOR.ID</code>.
     */
    public final TableField<JAuthorRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.AUTHOR.FIRST_NAME</code>.
     */
    public final TableField<JAuthorRecord, String> FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.AUTHOR.MIDDLE_NAME</code>.
     */
    public final TableField<JAuthorRecord, String> MIDDLE_NAME = createField("MIDDLE_NAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.AUTHOR.LAST_NAME</code>.
     */
    public final TableField<JAuthorRecord, String> LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.AUTHOR.DATE_OF_BIRTH</code>.
     */
    public final TableField<JAuthorRecord, Timestamp> DATE_OF_BIRTH = createField("DATE_OF_BIRTH", org.jooq.impl.SQLDataType.TIMESTAMP.precision(26).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.AUTHOR</code> table reference
     */
    public JAuthor() {
        this(DSL.name("AUTHOR"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.AUTHOR</code> table reference
     */
    public JAuthor(String alias) {
        this(DSL.name(alias), AUTHOR);
    }

    /**
     * Create an aliased <code>PUBLIC.AUTHOR</code> table reference
     */
    public JAuthor(Name alias) {
        this(alias, AUTHOR);
    }

    private JAuthor(Name alias, Table<JAuthorRecord> aliased) {
        this(alias, aliased, null);
    }

    private JAuthor(Name alias, Table<JAuthorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JAuthor(Table<O> child, ForeignKey<O, JAuthorRecord> key) {
        super(child, key, AUTHOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JPublic.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<JAuthorRecord, Long> getIdentity() {
        return Keys.IDENTITY_AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JAuthorRecord> getPrimaryKey() {
        return Keys.PK_AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JAuthorRecord>> getKeys() {
        return Arrays.<UniqueKey<JAuthorRecord>>asList(Keys.PK_AUTHOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JAuthor as(String alias) {
        return new JAuthor(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JAuthor as(Name alias) {
        return new JAuthor(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JAuthor rename(String name) {
        return new JAuthor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JAuthor rename(Name name) {
        return new JAuthor(name, null);
    }
}
