/*
 * This file is generated by jOOQ.
 */
package ru.yusdm.training.jooq.jooqgenerated;


import javax.annotation.Generated;

import ru.yusdm.training.jooq.jooqgenerated.tables.JAuthor;
import ru.yusdm.training.jooq.jooqgenerated.tables.JBook;
import ru.yusdm.training.jooq.jooqgenerated.tables.JBookAuthor;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final JAuthor AUTHOR = ru.yusdm.training.jooq.jooqgenerated.tables.JAuthor.AUTHOR;

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public static final JBook BOOK = ru.yusdm.training.jooq.jooqgenerated.tables.JBook.BOOK;

    /**
     * The table <code>PUBLIC.BOOK_AUTHOR</code>.
     */
    public static final JBookAuthor BOOK_AUTHOR = ru.yusdm.training.jooq.jooqgenerated.tables.JBookAuthor.BOOK_AUTHOR;
}
