/*
 * This file is generated by jOOQ.
 */
package ru.yusdm.training.jooq.jooqgenerated.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JBook implements Serializable {

    private static final long serialVersionUID = -519802649;

    private Long      id;
    private String    name;
    private String    contentAsText;
    private byte[]    contentAsPdf;
    private Integer   pagesNumber;
    private Timestamp publishDate;

    public JBook() {}

    public JBook(JBook value) {
        this.id = value.id;
        this.name = value.name;
        this.contentAsText = value.contentAsText;
        this.contentAsPdf = value.contentAsPdf;
        this.pagesNumber = value.pagesNumber;
        this.publishDate = value.publishDate;
    }

    public JBook(
        Long      id,
        String    name,
        String    contentAsText,
        byte[]    contentAsPdf,
        Integer   pagesNumber,
        Timestamp publishDate
    ) {
        this.id = id;
        this.name = name;
        this.contentAsText = contentAsText;
        this.contentAsPdf = contentAsPdf;
        this.pagesNumber = pagesNumber;
        this.publishDate = publishDate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContentAsText() {
        return this.contentAsText;
    }

    public void setContentAsText(String contentAsText) {
        this.contentAsText = contentAsText;
    }

    public byte[] getContentAsPdf() {
        return this.contentAsPdf;
    }

    public void setContentAsPdf(byte... contentAsPdf) {
        this.contentAsPdf = contentAsPdf;
    }

    public Integer getPagesNumber() {
        return this.pagesNumber;
    }

    public void setPagesNumber(Integer pagesNumber) {
        this.pagesNumber = pagesNumber;
    }

    public Timestamp getPublishDate() {
        return this.publishDate;
    }

    public void setPublishDate(Timestamp publishDate) {
        this.publishDate = publishDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JBook (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(contentAsText);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(pagesNumber);
        sb.append(", ").append(publishDate);

        sb.append(")");
        return sb.toString();
    }
}
